# Generated by Django 4.2.20 on 2025-05-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='banco',
            field=models.CharField(default='', max_length=100),
        ),
    ]
