# Generated by Django 5.2.1 on 2025-05-08 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoes', '0002_cartao_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 8, 10, 30)),
            preserve_default=False,
        ),
    ]
